eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  docker:
    compose:
      file: ./movie-service/compose.yaml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

server:
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024
  port: 0

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health